Color var cleanup
revelrylabs/wp-harmonium pull request #11
Opened 2019-08-09 17:56 UTC by vegasgeek

- Clean up the color vars
- Replace all media queries with the harmonium **breakpoint** syntax

2019-08-15 17:59 UTC, CheetoMao commented on assets/sass/modules/_tables.scss
> +		@include breakpoint($wp-admin-bar) {
Does this work? Harmonium doesn't have a `$sup-admim-bar` breakpoint unless you added one.

2019-08-15 18:00 UTC, CheetoMao requested changes
left one comment about  a breakpoint that Harmo doesn't have. Other than that, if the breakpoints are doing what you expect them to then 👍 everything "looks" good from this end

2019-08-16 15:46 UTC, vegasgeek commented
@CheetoMao Can you take a look at the changes I made? I added 3 new breakpoints to the list in order to match up with the available variables. I've done some testing of pages and things seem to be working well. I think this is a good start and we can tweak down the road as needed.

2019-08-16 17:13 UTC, CheetoMao approved these changes

2019-08-16 18:43 UTC, merged